# Generated by Django 2.1.3 on 2018-11-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='date_of_publication',
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_name',
            field=models.CharField(help_text='Publication name', max_length=500),
        ),
    ]
