# Generated by Django 2.1.3 on 2018-11-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(help_text='Book name', max_length=500),
        ),
    ]
