# Generated by Django 2.1.3 on 2018-11-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_auto_20181112_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(help_text='Conference name', max_length=500)),
                ('conference_url', models.URLField(null=True)),
            ],
        ),
    ]
