# Generated by Django 2.1.3 on 2018-11-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0005_conference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
